### PR TITLE
 dependencies slim part II

### PR DESCRIPTION
**Pull request by JoeZ99**
another one bites the dust

### CODE REVIEW

**Comment by ecoslado** [comment]
@JoeZ99 This PR can't be merged because of conflicts. Could you have a look, please?

**Comment by JoeZ99** [comment]
willdo

**Comment by JoeZ99** [comment]
@ecoslado, here you have it

**Comment by carlosescri** [comment]
@ecoslado what about this?

**Comment by ecoslado** [comment]
please  merge it. i  made joe to solve some conflicts and forgot merge

**Pull request merged**
